### ISSUE TITLE
HSL: hue = 0 ... Return value of Spatie\Color\Convert::hslValueToRgb() must be of the type array, none returned 

### ISSUE THREAD

**Issue by PhocaCz** [spatie/color#34]
Hi, 
I get an error, when hue value is 0:

Return value of Spatie\Color\Convert::hslValueToRgb() must be of the type array, none returned in
...\vendor\spatie\color\src\Convert.php:53

Testing:

```php
$red = '#fc0000';
$redHsl = Hex::fromString($red)->toHsl(); // hue protected => 0.0, saturation protected => 100.0, lightness protected => 49.411764705882355
$redRgb = $redHsl->toRgb();

```
or 

```php
$red = '#fc0000';
$redHsl = Hex::fromString($red)->toHsl(); // hue protected => 0.0, saturation protected => 100.0, lightness protected => 49.411764705882355
$redHslString = $redHsl->__toString();
$redRgb = Hsl::fromString($redHslString)->toRgb();
```

produces: 
**TypeError - Return value of Spatie\Color\Convert::hslValueToRgb() must be of the type array, none returned**
in *...\vendor\spatie\color\src\Convert.php:53*

Seems like the function hslValueToRgb() does not handle the value: $h == 0; properly?

Replacing from:
```php
$h = (360 + ($hue % 360)) % 360;  // hue values can be less than 0 and greater than 360. This normalises them into the range 0-360.
```
to:
```php
$h = (360 + ($hue % 360)) % 360;  // hue values can be less than 0 and greater than 360. This normalises them into the range 0-360.
		if ($h == 0) {
			$h = 360;
		}
```

solves the problem programmatically, but I have no idea, if it solves it correctly when it comes to creating colors. ???

Jan

**Comment by horuskol** [comment]
Looks like I forgot to test the limit cases like 0 hue.

`hsl(0, x%, y%)` is equivalent to `hsl(360, x%, y%)` - they should produce the same RGB values.

An even smaller fix is to trap 0 hue in the first condition on line 25:

```php
        if ($h >= 0 && $h <= 60) {
            return [round(($c + $m) * 255), round(($x + $m) * 255), round($m * 255)];
        }
```

I'll put a PR in to fix this.

**Comment by freekmurze** [comment]
We'll continue the conversation in #35
