### ISSUE TITLE
BUG : Hex color to HSL

### ISSUE THREAD

**Issue by ElRochito** [spatie/color#37]
Hi everyone,

For example, if I convert #a8a8a8 hex color to Hsl, I do : 

`Hex::fromString("#a8a8a8")->toHsl()`

I've got an error on `Spatie\Color::class` when delta is zero.

red, blue and green have same value (0.65882352941176) so `$cmin` and `$cmax` have same value

I think is the strict type on 

`if ($delta !== 0) {`

**Comment by freekmurze** [comment]
We'd accept a PR with tests that fixes this

**Comment by ElRochito** [comment]
See #38 :)

**Comment by freekmurze** [comment]
Thanks, we'll continue this in the PR
