### ISSUE TITLE
Converting Hex to Hsl for #000 & #fff gets division by zero

### ISSUE THREAD

**Issue by hodashirzad** [spatie/color#41]
Hi there

First of all thank you very much for this package as it is very useful, unfortunately when I try to convert the pure black or white colours it fails with division by zero error:

```php
Hex::fromString('#000000')->toHsl()
Hex::fromString('#ffffff')->toHsl()
```

I think the following fix will sort this issue out: 

In `src/Convert.php` line 77:

Replace this line:

```php
            $saturation = $delta / (1 - abs((2 * $lightness) - 1));
```

with the following:

```php
        if( $lightness > 0 && $lightness < 1) {
            $saturation = $delta / (1 - abs((2 * $lightness) - 1));
        }else {
            $saturation = 0;
        }
```

**Comment by Nielsvanpach** [comment]
Released in 1.2.4
