### ISSUE TITLE
Idea: Add opacity support to Hex colors

### ISSUE THREAD

**Issue by kodie** [spatie/color#63]
Hex colors can contain opacity data by adding them to the beginning of the color code.

For example: `#66000000` is black with 40% alpha transparency.

Some info here: https://gist.github.com/lopspower/03fb1cc0ac9f32ef38f4

Just an idea, I may try tackling this at some point but I also don't want it to be a breaking change so maybe the best way of going about it would be to add a fourth optional parameter to the Hex constructor.

**Comment by sebastiandedeyne** [comment]
This was added in https://github.com/spatie/color/pull/54 :)
