### ISSUE TITLE
Bug Division by Zero Rgb to Cmyk

### ISSUE THREAD

**Issue by stefanriehl** [spatie/color#79]
I am using version 1.5.2 (latest) on PHP 8.1 and getting an error by executing

`$cmyk = (new Spatie\Color\Rgb(0,0,0))->toCmyk();` or 
`$cmyk = (new Spatie\Color\Hex('00', '00', '00'))->toCmyk();`

Error is:

`PHP Error:  Division by zero in /.../vendor/spatie/color/src/Convert.php on line 67`

The error is related to [https://github.com/spatie/color/blob/main/src/Convert.php#L57](https://github.com/spatie/color/blob/main/src/Convert.php#L57)

When red, green and blue are 0, then `$keyNeg` is also 0 

I can only do a PR maybe in 2 weeks or so.

**Comment by kodie** [comment]
This was fix with #82 and should be closed.
