### ISSUE TITLE
toHSL Uppercase letters Bug?

### ISSUE THREAD

**Issue by wintstar** [spatie/color#85]
https://github.com/spatie/color/blob/2a3bb4e23434cf051cea5467d2e2d9924dd4969f/src/CIELab.php#L94

https://github.com/spatie/color/blob/2a3bb4e23434cf051cea5467d2e2d9924dd4969f/src/Xyz.php#L100

It should be toHsl?

`return $this->toRgb()->toHsl(); `

**Comment by freekmurze** [comment]
Yeah, although it'll work as PHP function names are not case sensitive I believe.

Feel free to PR improvements!
