### ISSUE TITLE
Contrast should return an int or float?

### ISSUE THREAD

**Issue by NiklasBr** [spatie/color#88]
Function signature says `: float`
https://github.com/spatie/color/blob/2a3bb4e23434cf051cea5467d2e2d9924dd4969f/src/Contrast.php#L7

but the return value is cast to `int`:

https://github.com/spatie/color/blob/2a3bb4e23434cf051cea5467d2e2d9924dd4969f/src/Contrast.php#L27-L31

It could be improved by changing the return cast to `(float)`, but I am not sure if there are any side effects to I want to ask about what is the intent here before creating a PR.

**Comment by NiklasBr** [comment]
@timvandijck why close this issue while I was waiting for you?

**Comment by timvandijck** [comment]
> [@timvandijck](https://github.com/timvandijck) why close this issue while I was waiting for you?

I'm sorry the bot closed it automatically due to inactivity.

For your initial question: don't be afraid to just make the PR. The package uses snapshots for the images so any unwanted side effects should result in a failing test.
