### ISSUE TITLE
Fails with HSL with floats

### ISSUE THREAD

**Issue by mwargan** [spatie/color#89]
Given a value like hsl(221, 11.52%, 32.35%), `Factory::fromString(hsl(221, 11.52%, 32.35%))->toHex();` fails to parse the colour.

**Comment by Afrowson** [comment]
I got the same issue with an HSLA value:

```
Hsla color string `hsla(357,100%,44.5%,1)` is malformed. 
An hsla color contains hue, saturation, lightness and alpha values, wrapped in `hsl()`, e.g. `hsl(300,10%,50%,0.25)`.
```
this error message is funny as it is wrong as well. should be `wrapped in 'hsla()'`
